# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4b13562fc86b3d9ec6efb7af11eb5ea89e0508899e164875fe286c922ef6396c77faf08690f1c2d9c7cf2271d5a562172d120947bfcb0fb8d4eb4da7f0db8d9

test:
  secret_key_base: 4836e9ef5c291dfdee2935dc98b9e340fe9376c802349e62c2caa8959e60bcac8e9f4e7a20f6f3cff83cc8d9451494b9e0dfd24844a4b7afcc902cb45c8c8c59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
